version: '3'

services:
  nodejs:
    build: .
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
