version: '3'

services:
  node-app:
    depends_on:
      - mongodb
    build: .
    image: nodejs
    container_name: node_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:3000"
    environment:
      - MONGODB_HOST=mongodb # this is the name of the service below
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_PORT=$MONGODB_PORT
      - JWT_ACCESS_TOKEN_KEY=$JWT_ACCESS_TOKEN_KEY
      - JWT_REFRESH_TOKEN_KEY=$JWT_REFRESH_TOKEN_KEY
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
