# .github/workflows/cicd.yml
name: Deploy

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push_to_registry_dev:
    name: Push Docker image dev to Docker Hub
    runs-on: ubuntu-latest
    environment: 
      name: DEV
      url: https://github.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # - name: UnitTest ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-dev:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-dev:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}

  build_and_push_to_registry_prod:
    name: Push Docker image prod to Docker Hub
    runs-on: ubuntu-latest
    environment: 
      name: PROD
      url: https://github.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # - name: UnitTest ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-prod:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-prod:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
