# .github/workflows/deploy-ci-cd-qa-uat.yml
name: Deploy QA/UAT

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches:
      - dev

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-qa:
    name: Push Docker Image QA To Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: https://github.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{secrets.ENV_FILE}}" > .env
          echo NODE_LOCAL_PORT=${NODE_LOCAL_PORT} >> .env
          echo MONGODB_HOST=${MONGODB_HOST} >> .env
          echo MONGODB_PORT=${MONGODB_PORT} >> .env
          echo MONGODB_DATABASE=${MONGODB_DATABASE} >> .env

      # - name: UnitTest ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18
      #     cache: 'npm'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-qa:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-qa:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}

  deploy-uat:
    name: Push Docker Image UAT To Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: UAT
      url: https://github.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-uat:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-uat:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
