# .github/workflows/deploy-ci-cd-prod.yml
name: Deploy PROD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_prod:
    name: Push Docker Image Prod To Docker Hub
    runs-on: ubuntu-latest
    environment: 
      name: PROD
      url: https://github.com
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: "Create env file"
        run: |
          echo "${{secrets.ENV_FILE}}" > .env
          echo NODE_LOCAL_PORT=${NODE_LOCAL_PORT} >> .env
          echo MONGODB_HOST=${MONGODB_HOST} >> .env
          echo MONGODB_PORT=${MONGODB_PORT} >> .env
          echo MONGODB_DATABASE=${MONGODB_DATABASE} >> .env
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-prod:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-sample-prod:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
